### ISSUE TITLE
Dependency 

### ISSUE THREAD

**Issue by delwende** [drcandacemakedamoore/cleanX#14]
Create a report to help us improve

**Describe the bug**
 tesserocr

**To Reproduce**

    pip install cleanx
**Expected behavior**
ERROR: Failed building wheel for tesserocr
  Running setup.py clean for tesserocr

**Screenshots**

**Your computer environment info: (please complete the following information):**
Ubuntu 16.

    OS: [e.g. Linux]
    Python V=version [e.g. 3.7]
I think you should add minimum requirement in the readme file

**Comment by wvxvw** [comment]
`tesserocr` package is just a binding for the tesseract library, so you would need to install the library itself.

You can see the other dependencies in our CI script: https://github.com/drcandacemakedamoore/cleanX/blob/main/.github/workflows/on-commit.yml#L8

This is the gist of it:

``` sh
sudo apt-get install -y libleptonica-dev tesseract-ocr-all libtesseract-dev python3-opencv
```

**Comment by drcandacemakedamoore** [comment]
Please note the new installation script and notes. I think we can close the issue as soon as the readme is updated.

**Comment by drcandacemakedamoore** [comment]
Readme updated on issue, close...
