### ISSUE TITLE
Simple way to install on kaggel

### ISSUE THREAD

**Issue by delwende** [drcandacemakedamoore/cleanX#15]
Installing tesserocr through pip doesn't work. You should install with conda
conda install -c conda-forge tesserocr

!pip install git+https://github.com/drcandacemakedamoore/cleanX.git

**Comment by drcandacemakedamoore** [comment]
Thank you for the feedback! As Oleg said, we are looking for a better way to package the dependencies so these issues will not come up. However until we do, I will be encouraging this way. I used conda myself.
