### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by delwende** [drcandacemakedamoore/cleanX#16]
Create a report to help us improve
We need to declare the variable outside the for loop
**Describe the bug**
find_by_sample_upper
![image](https://user-images.githubusercontent.com/9020231/125177895-e1f7c480-e1df-11eb-9f67-015b11df4c48.png)

**Comment by drcandacemakedamoore** [comment]
Yes, it seems I had made the wrong indentation in the version of the function that was on the main branch. You should be able to use the newly updated (a few seconds ago) function. For now please just copy the function directly (line 631 cleanX.py) as we plan to rebase everything and have a new differently structured release in a few days.
