### ISSUE TITLE
Documentation needs to be per-version

### ISSUE THREAD

**Issue by wvxvw** [drcandacemakedamoore/cleanX#32]
It appears that neither of two Sphinx extensions that supposedly accomplish this don't actually work: 

* https://github.com/Holzhaus/sphinx-multiversion doesn't support `setuptools` integration
* https://github.com/sphinx-contrib/sphinxcontrib-versioning is obsolete (doesn't support the current version of Sphinx).

So, it looks like this is going to be a lot of manual labor involving CSS and HTML of Sphinx templates...

**Comment by drcandacemakedamoore** [comment]
But please not on the main branch any time this month.

**Comment by drcandacemakedamoore** [comment]
I think the new develop branch will soon be a new version, and very few people were using an old version. We may need per version docs in the future...but this is fine for now.
