### ISSUE TITLE
Clutter in documentation

### ISSUE THREAD

**Issue by wvxvw** [drcandacemakedamoore/cleanX#33]
In retrospect, using https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html was a bad idea. The code it generates is awful and impossible to control. In particular, there's no way to disable or enable special methods on per-class basis. Similarly for inheritance etc.

Apparently, we need to replace this with something else that would generate sensible documentation pages. There's no hope that `sphinx-apidoc` will ever improve.

**Comment by drcandacemakedamoore** [comment]
So long as we do not do it on the main branch while we are under review at JOSS...

**Comment by drcandacemakedamoore** [comment]
Looks like you managed to fix some of the worst of this wvxvw, thanks!
