### ISSUE TITLE
Language cleanup and typos

### ISSUE THREAD

**Issue by henrykironde** [drcandacemakedamoore/cleanX#48]
CleanX uses some sensitive language that may offend some users. I would recommend that you remove words like `idiots` since it is against the code of conduct for Joss.

There are typos in the doc strings, like """This class allows normalization by throwing off exxtreme values on" It would be nice to look through the doc strings and try to remove the typos.

Note: I am still failing to install CleanX, but I think it is some complications with my Conda setup. I will keep you updated. My target is to finish with the review and final decision in 14 days.

Ref: openjournals/joss-reviews#3632

**Comment by drcandacemakedamoore** [comment]
Thank you! I will run over all the doc-strings for typos before midnight
today, and try to remove any offensive language. O.S., please see if there
is anything we can do to help with installation.

**Comment by drcandacemakedamoore** [comment]
Hi  @henrykironde  , if I understand you correctly we do not need to keep the branches frozen. I am therefore going to push a new version very soon so our main branch can be clean of potentially offensive comments, as well as include the new groups of functions on image quality and noise.

**Comment by drcandacemakedamoore** [comment]
OK, a new less offensive version is on the main... we are currently reviewing user installation issues @henrykironde, so if you have any additional notes on that please let us know.

**Comment by henrykironde** [comment]
Thank you for the updates, `pip install cleanX` works fine now on Mac and ubuntu.

Please add instructions on how to install `tesseract` or let the users know that `tesseract` is required before installing cleanX.  On Mac I had to run `brew install tesseract`.
