### ISSUE TITLE
Examples and workflow_demo 

### ISSUE THREAD

**Issue by henrykironde** [drcandacemakedamoore/cleanX#54]
@drcandacemakedamoore 👍🏿 for getting this to finally install smoothly. Some issues that I have are detailed below.

**README.md Example:** 

- [ ] Add s check to see if the path exist `cleaned` or always delete it first and then make a new one.
```python
dst = 'cleaned'
if not  os.path.exists(dst):
    os.mkdir(dst)
```
```python
dst = 'cleaned'
os.rmdir(dst)
os.mkdir(dst)
```

Improve this  README.md example, I had to install SimpleITK and PyDICOM. You could add this to required dependencies.

```python
(cleanx) henrysenyondo ~/Downloads/cleanX [main] $ python examplecleanX.py 
WARNING:root:Don't know how to find Tesseract library version
/Users/henrysenyondo/Downloads/cleanX/cleanX/dicom_processing/__init__.py:37: UserWarning: 
Neither SimpleITK nor PyDICOM are installed.

Will not be able to extract information from DICOM files.

  warnings.warn(
Traceback (most recent call last):
  File "examplecleanX.py", line 36, in <module>
    from cleanX.dicom_processing import DicomReader
ImportError: cannot import name 'DicomReader' from 'cleanX.dicom_processing' (/Users/henrysenyondo/Downloads/cleanX/cleanX/dicom_processing/__init__.py)
(cleanx) henrysenyondo ~/Downloads/cleanX [main] $

```

Use a path that does actually exist in the repo `src = GlobSource('/images/to/clean/*.jpg')`

**workflow_demo examples**:

- [ ] Use paths that do exist in the repo, or add a comment to point to the data to be used in that given example. Assume that the user is going to run the examples in the root directory, so all paths could be relative to that directory. In the example from cleanX/workflow_demo/classes_workflow.ipynb
- [ ] Refactor the workflow_demo files, rename them appropriately remove files not needed.

**Comment by henrykironde** [comment]
I think this covers all that is left from my side. If I can get those examples to run, and I evaluate the results, I will be done with much of the review.

**Comment by wvxvw** [comment]
Hi @henrykironde.

I've done some work on your bullet points. You can see it here: https://github.com/drcandacemakedamoore/cleanX/commit/6f725e923ec3bda2b688d5c224a48fd1a61f2e06

Some explanation:

> Add s check to see if the path exist cleaned or always delete it first and then make a new one.

The code in the readme is just an illustration. There isn't really production-grade code that can assuredly delete directory and guarantee that it exists when a program will try to access it. It's really up to the user of the program to make sure the directory exists and is *sufficiently* empty. I don't really want to go into details on how this may happen, but some obvious examples would be insufficient permissions, another filesystem mounted inside the target directory, locked files in target directory and so on. I don't think that trying to deal with those cases is a good place in the readme.

Anyways, I added something that shows intent that the directory needs to be probably empty.

>  I had to install SimpleITK and PyDICOM.

Yeah, sorry, that wasn't covered in the installation instructions. But it was possible before too. At least the plan was that PyDICOM and SimpleITK be defined as optional dependencies. We actually run tests in CI to make sure that the code that doesn't have to deal with DICOM files is independent of those libraries.

Anyways, I updated the readme to mention how to install optional dependencies.

**Comment by henrykironde** [comment]
@wvxvw, I recommend that you reduce the explanations and please try to clean up your package as advised. This will make the review faster. I do believe that all the recommendations I have made, from the beginning, have made your package easy to install, easy to understand, easy to review, and to the level of a good software product standard.

**Comment by drcandacemakedamoore** [comment]
@henrykironde the cleanX/workflow_demo/classes_workflow.ipynb is now redone. Some of the code needed updating, as well as putting the files where people can get them to run the notebook. Thanks for your help.  One issue I want to ask about is that there were some minor updates on the paper, and we may add an author. Should we get Wheedon to rebuild the paper again to make sure the paper will actually build properly?

**Comment by henrykironde** [comment]
Thanks for working on the examples. I am really excited to see the final product of sample raw data and then the cleaned/processed data. 

Rebuilding the paper should not be a concern(it is automatic). We need to have all revisions in and working smoothly, then after the reviews decide (accept/reject) the rest can follow.

**Comment by henrykironde** [comment]
@drcandacemakedamoore let me know if there any updated with the examples. No rush.

**Comment by drcandacemakedamoore** [comment]
If you mean did I refactor the workflow demos to use paths from the repo- yes I did. Also in the additional demos folder ([additional_demos](https://github.com/drcandacemakedamoore/cleanX/tree/main/additional_demos) most of the data used can be taken from the matplotlib library. Is that what you meant by examples?

**Comment by drcandacemakedamoore** [comment]
Oops, I just found one notebook, for_medical_people.ipynb, with a reference to a folder not inside workflow-demo because I was updating the workflow. I will change it ASAP.

**Comment by drcandacemakedamoore** [comment]
Hi @henrykironde I heard you wanted to see a set of images processed. Is what we have at the end of the [classes workflo demo](https://github.com/drcandacemakedamoore/cleanX/blob/main/workflow_demo/classes_workflow.ipynb) enough, or do you want to see a whole set done from cleaning forward?

**Comment by henrykironde** [comment]
<img width="1285" alt="Screen Shot 2022-05-15 at 4 59 20 PM" src="https://user-images.githubusercontent.com/5192965/168493541-051630c1-00f9-4c8d-b80a-d3a3eca26366.png">

<img width="1211" alt="Screen Shot 2022-05-15 at 5 00 36 PM" src="https://user-images.githubusercontent.com/5192965/168493583-41e5efd5-947f-406b-bc04-9d446553a234.png">

I found these two workflows not working.

**Comment by henrykironde** [comment]
Do we need this cell, Looks we can clean it  up / remove it
<img width="1197" alt="Screen Shot 2022-05-15 at 5 49 33 PM" src="https://user-images.githubusercontent.com/5192965/168495269-70f7dcc2-b996-4d5f-91da-cd4d5e8d476d.png">

**Comment by wvxvw** [comment]
Hi Henry.

The first one looks like a problem with the CV2 version. I'll have to
research this to understand what's wrong there.

Makeda will know more about the second question (afaikt, this is an output
of a utility that checks the environment compatibility, so, could be
important).

**Comment by henrykironde** [comment]
> Makeda will know more about the second question (afaikt, this is an output
of a utility that checks the environment compatibility, so, could be
important).
Okey, we can leave that.

**Comment by henrykironde** [comment]
It would be nice if me merge develop into main after fixing the issues with CV2 or removing the examples that don't work. I think with that this issue will be ready for closing.

**Comment by drcandacemakedamoore** [comment]
I am almost certain the errors come from a cv2 version problem after
reviewing documentation on cv2. We will have to specify the cv2 version
more narrowly. After this has been repaired, we will push everything on the
develop branch into the main and let you know.

Makeda

**Comment by wvxvw** [comment]
The problem with CV2 should be fixed now (hopefully, didn't break anything
else.

Turns out, CV2 has multiple different Python bindings, and the one that has
hashing functions is opencv-contrib-python. This should be the one we use
now too.

As for updating the master: probably tonight.

**Comment by henrykironde** [comment]
Closing because the example are workflows have been amended and tested.
