### ISSUE TITLE
Testing builds on Windows and Mac

### ISSUE THREAD

**Issue by fdiblen** [drcandacemakedamoore/cleanX#65]
It would be nice the builds are tested on Windows and Mac. One can do that using GitHub actions: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-adding-configurations
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on

**Comment by wvxvw** [comment]
Hi @fdiblen , perhaps you've overlooked it. Please take a look at the tests run in Github Actions here, for example: https://github.com/drcandacemakedamoore/cleanX/runs/6907395039?check_suite_focus=true

We are testing Windows builds for Python Anaconda distribution 3.7, 3.8 and 39. Similarly, for MacOS.

Take a look at this part of the README.md: https://github.com/drcandacemakedamoore/cleanX#amd64-x86 it lists supported platforms. If the platform is listed there, it has an entry in the test matrix too.

**Comment by fdiblen** [comment]
Hey @wvxvw,

Great! Yes, I overlooked. 
I think it would be nice to show status badges in README.md to show the build status for each OS/Python version.
