### ISSUE TITLE
License and source of data files

### ISSUE THREAD

**Issue by fdiblen** [drcandacemakedamoore/cleanX#66]
It is not clear where the datasets in `additional_demos` and `workflow_demo` are coming from and what license they have.

**Comment by drcandacemakedamoore** [comment]
Good point, I'll work on updating this issue.

**Comment by drcandacemakedamoore** [comment]
Both the additional_demos (which has one public domain image) and Readme have been updated. The readme is updated to mention that the X-ray images are creative commons Attribution 4.0 International. I had previously reached out to Praveen (the guy who made the image dataset we pull from) to make sure he was OK with the images being used as we did, but it is more correct to include the license info . Thank you for catching this.
